hotel= input('Какой отель вы хотите заказать?')
status=input('Эконом или Люкс?')
options=input('Завтрак,Обед,Ужин или всё вместе?')
taxi=input('Вы нуждететесь в доставке до отеля?')
print('Отель:',hotel)
print('Вид отеля:',status)
print('Дополнительные опции:',options)
print('Доставка до отеля:',taxi)